export const GET_CART_FROM_STORAGE = "GET_CART_FROM_STORAGE";
export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const UPDATE_CART = "UPDATE_CART";

export const CLEAR_CART = "CLEAR_CART";

export const GET_CART_TOTAL = "GET_CART_TOTAL";

export const GET_WISHES_FROM_STORAGE = "GET_WISHES_FROM_STORAGE";

export const ADD_TO_WISHES = "ADD_TO_WISHES";

export const REMOVE_FROM_WISHES = "REMOVE_FROM_WISHES";

export const UPDATE_WISHES = "UPDATE_WISHES";

export const CLEAR_WISHES = "CLEAR_WISHES";
