
/////get all products
export const  GET_PRODUCTS_LOAD ="GET_PRODUCTS_LOAD";
export const  GET_PRODUCTS_SUCCESS ="GET_PRODUCTS_SUCCESS";
export const  GET_PRODUCTS_FAIL ="GET_PRODUCTS_FAIL";


/////get product by id
export const  GET_PRODUCT_BY_ID_LOAD ="GET_PRODUCT_BY_ID_LOAD";
export const  GET_PRODUCT_BY_ID_SUCCESS ="GET_PRODUCT_BY_ID_SUCCESS";
export const  GET_PRODUCT_BY_ID_FAIL ="GET_PRODUCT_BY_ID_FAIL";


////get genders
export const  GET_GENDERS_LOAD ="GET_GENDERS_LOAD";
export const  GET_GENDERS_SUCCESS ="GET_GENDERS_SUCCESS";
export const  GET_GENDERS_FAIL ="GET_GENDERS_FAIL";
 


///// get all category name

export const  GET_CATEGORYS_LOAD ="GET_CATEGORYS_LOAD";
export const  GET_CATEGORYS_SUCCESS ="GET_CATEGORYS_SUCCESS";
export const  GET_CATEGORYS_FAIL ="GET_CATEGORYS_FAIL";

///// get PRODUCTS BY GENDER AND BY CATEGORY 
export const  GET_PRODUCTS_BY_GC_LOAD ="GET_PRODUCTS_BY_GC_LOAD";
export const  GET_PRODUCTS_BY_GC_SUCCESS ="GET_PRODUCTS_BY_GC_SUCCESS";
export const  GET_PRODUCTS_BY_GC_FAIL ="GET_PRODUCTS_BY_GC_FAIL";


///// get PRODUCTS BY GENDER AND BY CATEGORY & distict title
export const  GET_PRODUCTS_BY_GC_DT_LOAD ="GET_PRODUCTS_BY_GC_DT_LOAD";
export const  GET_PRODUCTS_BY_GC_DT_SUCCESS ="GET_PRODUCTS_BY_GC_DT_SUCCESS";
export const  GET_PRODUCTS_BY_GC_DT_FAIL ="GET_PRODUCTS_BY_GC_DT_FAIL";


///// get all distinct colors by title

export const  GET_COLORS_LOAD ="GET_COLORS_LOAD";
export const  GET_COLORS_SUCCESS ="GET_COLORS_SUCCESS";
export const  GET_COLORS_FAIL ="GET_COLORS_FAIL";


///get all titles  sizes
export const  GET_TITLES_SIZES_LOAD ="GET_TITLES_SIZES_LOAD";
export const  GET_TITLES_SIZES_SUCCESS ="GET_TITLES_SIZES_SUCCESS";
export const  GET_TITLES_SIZES_FAIL ="GET_TITLES_SIZES_FAIL";

